runtime: nodejs16
service: default
env_variables:
  APP_ENV: "production"
  SERVICE_ACCOUNT_PATH: "../service-account-key.json"
  SENDGRID: "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"
  FIREBASE_WEB_API_KEY: "AIzaSyCXYtcxvEb1dYpLv2q-uDZYQBEnyHqv-zY"
  REGISTER_CODE_KEY: "81P11pJtw1i5O0vRWr5IsX2k76N499l4"
  STRIPE_PUBLIC_KEY: "pk_live_51ML1EFFHsPcDb9h9lS3LyStvJgZr6DJOoq1xRgLt9jHQV8Fh8o1krokvM6Z5N1X5SUhUNl1gkCbNN3depiBndr8C00sgxLolu7"
  STRIPE_SECRET_KEY: "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"