runtime: nodejs18
service: default
env_variables:
  APP_ENV: "production"
  SERVICE_ACCOUNT_PATH: "../service-account-key.json"
  SENDGRID: "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"
  FIREBASE_WEB_API_KEY: "AIzaSyCXYtcxvEb1dYpLv2q-uDZYQBEnyHqv-zY"
  REGISTER_CODE_KEY: "81P11pJtw1i5O0vRWr5IsX2k76N499l4"
  APP_URL: "https://app.priorli.com"
  PAYMENT_WEBHOOK_SECRET: "whsec_cf9zQCMh3iboI3QCRrHhpsBFQKI1Cv15"
  PAYMENT_CONNECT_ACCOUNT_WEBHOOK_SECRET: "whsec_co5QsYy64jvumuZknXQPpD4NVxQV02QV"
  STRIPE_PUBLIC_KEY: "pk_live_51ML1EFFHsPcDb9h9lS3LyStvJgZr6DJOoq1xRgLt9jHQV8Fh8o1krokvM6Z5N1X5SUhUNl1gkCbNN3depiBndr8C00sgxLolu7"
  STRIPE_SECRET_KEY: "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"
  OPENAI_API_KEY: "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"
  AWS_ACCESS_KEY_ID: "AKIA4KZ3DN3TU3DMUNVU"
  AWS_SECRET_ACCESS_KEY: "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"
  PINECONE_ENVIRONMENT: "us-west1-gcp-free"
  PINECONE_API_KEY: "3c4ffd26-7767-42cf-a675-c76727b7a211"
