runtime: nodejs16
service: default
env_variables:
  APP_ENV: "production"
  SERVICE_ACCOUNT_PATH: "../service-account-key.json"
  SENDGRID: "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"
  FIREBASE_WEB_API_KEY: "AIzaSyCXYtcxvEb1dYpLv2q-uDZYQBEnyHqv-zY"
  REGISTER_CODE_KEY: "81P11pJtw1i5O0vRWr5IsX2k76N499l4"
  APP_URL: "https://app.priorli.com"
  PAYMENT_WEBHOOK_SECRET: "whsec_1rooNgcLqLHZnZoQh46EQRa3iYdlUopT"
  STRIPE_PUBLIC_KEY: "pk_test_51ML1EFFHsPcDb9h9TUNA7FHQwf38mzM9deXsbcoFDznW96gaCgysaLtzI9fXYj7CxzRIvQKdJzplA4C4R4H2qQbF00pRPPIA0v"
  STRIPE_SECRET_KEY: "sk_test_51ML1EFFHsPcDb9h9D5WUIUB9Gacjgvq4vdu5yXDy15RNXNpriOaWWCffpXUuIT7VCmSDIaZejXnOGRYg001J0kOm0034uHWjaq"
